// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using quanlyphongkham.Data;

#nullable disable

namespace quanlyphongkham.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("quanlyphongkham.Models.BacSi", b =>
                {
                    b.Property<int>("MaBacSi")
                        .HasColumnType("int");

                    b.Property<string>("ChuyenKhoaChinh")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MoTaChuyenMon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoChungChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SoNamKinhNghiem")
                        .HasColumnType("int");

                    b.HasKey("MaBacSi");

                    b.ToTable("BacSi");
                });

            modelBuilder.Entity("quanlyphongkham.Models.BaoCao", b =>
                {
                    b.Property<int>("MaBaoCao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaoCao"));

                    b.Property<string>("DuongDanFile")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiBaoCao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("TenBaoCao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaBaoCao");

                    b.HasIndex("NguoiTao");

                    b.ToTable("BaoCao");
                });

            modelBuilder.Entity("quanlyphongkham.Models.BenhNhan", b =>
                {
                    b.Property<int>("MaBenhNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBenhNhan"));

                    b.Property<string>("DiUng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChuBacSi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoaiBenhNhan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TienSuBenh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBenhNhan");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("BenhNhan", t =>
                        {
                            t.HasTrigger("trg_BenhNhan_TaoQuanHeBanThan");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("quanlyphongkham.Models.CauHinhHeThong", b =>
                {
                    b.Property<int>("MaCauHinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCauHinh"));

                    b.Property<string>("GiaTri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiCauHinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhat")
                        .HasColumnType("int");

                    b.Property<string>("TenCauHinh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaCauHinh");

                    b.HasIndex("NguoiCapNhat");

                    b.ToTable("CauHinhHeThong");
                });

            modelBuilder.Entity("quanlyphongkham.Models.ChamCong", b =>
                {
                    b.Property<int>("MaChamCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChamCong"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("GioRa")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("GioVao")
                        .HasColumnType("time");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLamViec")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SoGioLam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaChamCong");

                    b.HasIndex("MaNhanVien", "NgayLamViec")
                        .IsUnique();

                    b.ToTable("ChamCong");
                });

            modelBuilder.Entity("quanlyphongkham.Models.ChiTietHoSo", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal?>("DonGia")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("int");

                    b.Property<int>("MaHoSo")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaDichVu");

                    b.HasIndex("MaHoSo");

                    b.ToTable("ChiTietHoSo");
                });

            modelBuilder.Entity("quanlyphongkham.Models.DichVu", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDichVu"));

                    b.Property<string>("LoaiDichVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ThoiGianThucHien")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaDichVu");

                    b.ToTable("DichVu");
                });

            modelBuilder.Entity("quanlyphongkham.Models.GheNhaKhoa", b =>
                {
                    b.Property<int>("MaGhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGhe"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBatDauBaoTri")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThucBaoTri")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenGhe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ViTri")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaGhe");

                    b.ToTable("GheNhaKhoa");
                });

            modelBuilder.Entity("quanlyphongkham.Models.GiaDichVu", b =>
                {
                    b.Property<int>("MaGiaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiaDichVu"));

                    b.Property<decimal>("DonGia")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayApDung")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.HasKey("MaGiaDichVu");

                    b.HasIndex("MaDichVu");

                    b.ToTable("GiaDichVu");
                });

            modelBuilder.Entity("quanlyphongkham.Models.HinhAnhXQuang", b =>
                {
                    b.Property<int>("MaHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinhAnh"));

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaHoSo")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayUpload")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiUpload")
                        .HasColumnType("int");

                    b.Property<string>("TenFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHinhAnh");

                    b.HasIndex("MaHoSo");

                    b.HasIndex("NguoiUpload");

                    b.ToTable("HinhAnhXQuang");
                });

            modelBuilder.Entity("quanlyphongkham.Models.HoSoBenhAn", b =>
                {
                    b.Property<int>("MaHoSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoSo"));

                    b.Property<string>("ChanDoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DaThanhToan")
                        .HasColumnType("bit");

                    b.Property<string>("DonThuoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HenTaiKham")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoiDan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaBacSi")
                        .HasColumnType("int");

                    b.Property<int>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<int?>("MaGhe")
                        .HasColumnType("int");

                    b.Property<int?>("MaLichHen")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayKham")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongPhapDieuTri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrieuChung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHoSo");

                    b.HasIndex("MaBacSi");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaGhe");

                    b.HasIndex("MaLichHen");

                    b.ToTable("HoSoBenhAn");
                });

            modelBuilder.Entity("quanlyphongkham.Models.LichBaoTriGhe", b =>
                {
                    b.Property<int>("MaBaoTri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaoTri"));

                    b.Property<int>("MaGhe")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBaoTri")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiBaoTri")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaBaoTri");

                    b.HasIndex("MaGhe");

                    b.HasIndex("NguoiBaoTri");

                    b.ToTable("LichBaoTriGhe");
                });

            modelBuilder.Entity("quanlyphongkham.Models.LichHen", b =>
                {
                    b.Property<int>("MaLichHen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichHen"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("GioHen")
                        .HasColumnType("time");

                    b.Property<string>("KenhDatLich")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LyDoKham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaBacSi")
                        .HasColumnType("int");

                    b.Property<int>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("int");

                    b.Property<int?>("MaGhe")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhanVienXacNhan")
                        .HasColumnType("int");

                    b.Property<int?>("MaTaiKhoanDatLich")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHen")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuanHe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianXacNhan")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaLichHen");

                    b.HasIndex("MaBacSi");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaDichVu");

                    b.HasIndex("MaGhe");

                    b.HasIndex("MaNhanVienXacNhan");

                    b.HasIndex("MaTaiKhoanDatLich");

                    b.ToTable("LichHen", t =>
                        {
                            t.HasTrigger("trg_AuditLog_LichHen");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("quanlyphongkham.Models.LichLamViec", b =>
                {
                    b.Property<int>("MaLich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLich"));

                    b.Property<string>("CaLam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int>("Thu")
                        .HasColumnType("int");

                    b.HasKey("MaLich");

                    b.HasIndex("MaNhanVien", "Thu", "CaLam")
                        .IsUnique();

                    b.ToTable("LichLamViec");
                });

            modelBuilder.Entity("quanlyphongkham.Models.LoaiNhanVien", b =>
                {
                    b.Property<int>("MaLoaiNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiNV"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoaiNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoaiNV");

                    b.ToTable("LoaiNhanVien");
                });

            modelBuilder.Entity("quanlyphongkham.Models.Luong", b =>
                {
                    b.Property<int>("MaLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLuong"));

                    b.Property<decimal?>("KhauTru")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("LuongCoBan")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTinhLuong")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PhanTramHoaHong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SoTienHoaHong")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal?>("Thuong")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("TongLuong")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLuong");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("Luong");
                });

            modelBuilder.Entity("quanlyphongkham.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("BangCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuyenKhoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiThieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaLoaiNV")
                        .HasColumnType("int");

                    b.Property<int>("MaTaiKhoanNV")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("SoNamKinhNghiem")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianBatDauLam")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaLoaiNV");

                    b.HasIndex("MaTaiKhoanNV");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("quanlyphongkham.Models.NhapKho", b =>
                {
                    b.Property<int>("MaNhapKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhapKho"));

                    b.Property<decimal?>("DonGiaNhap")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaVatTu")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiNhap")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("MaNhapKho");

                    b.HasIndex("MaVatTu");

                    b.HasIndex("NguoiNhap");

                    b.ToTable("NhapKho", t =>
                        {
                            t.HasTrigger("trg_CapNhatTonKhoNhap");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("quanlyphongkham.Models.PhanQuyen", b =>
                {
                    b.Property<int>("MaPhanQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanQuyen"));

                    b.Property<int>("MaLoaiNV")
                        .HasColumnType("int");

                    b.Property<bool>("QuanLyKho")
                        .HasColumnType("bit");

                    b.Property<bool>("QuanLyNhanSu")
                        .HasColumnType("bit");

                    b.Property<bool>("SuaHoSo")
                        .HasColumnType("bit");

                    b.Property<bool>("SuaLich")
                        .HasColumnType("bit");

                    b.Property<bool>("XemDoanhThu")
                        .HasColumnType("bit");

                    b.Property<bool>("XemHoSo")
                        .HasColumnType("bit");

                    b.Property<bool>("XemLich")
                        .HasColumnType("bit");

                    b.HasKey("MaPhanQuyen");

                    b.HasIndex("MaLoaiNV")
                        .IsUnique();

                    b.ToTable("PhanQuyen");
                });

            modelBuilder.Entity("quanlyphongkham.Models.QuanHeBenhNhan", b =>
                {
                    b.Property<int>("MaQuanHe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuanHe"));

                    b.Property<int>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuanHe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaQuanHe");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaTaiKhoan", "MaBenhNhan")
                        .IsUnique();

                    b.ToTable("QuanHeBenhNhan");
                });

            modelBuilder.Entity("quanlyphongkham.Models.TaiKhoanNguoiDung", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("LyDoKhoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("OTP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ThoiGianOTP")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTaiKhoan");

                    b.ToTable("TaiKhoanNguoiDung");
                });

            modelBuilder.Entity("quanlyphongkham.Models.TaiKhoanNhanVien", b =>
                {
                    b.Property<int>("MaTaiKhoanNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoanNV"));

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTaiKhoanNV");

                    b.ToTable("TaiKhoanNhanVien");
                });

            modelBuilder.Entity("quanlyphongkham.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<string>("APIResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CoTraGop")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThucThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KeHoachTraGop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaHoSo")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiThu")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaHoSo");

                    b.HasIndex("NguoiThu");

                    b.ToTable("ThanhToan");
                });

            modelBuilder.Entity("quanlyphongkham.Models.ThanhToanOnline", b =>
                {
                    b.Property<int>("MaThanhToanOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToanOnline"));

                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaThanhToan")
                        .HasColumnType("int");

                    b.Property<decimal?>("SoTien")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaThanhToanOnline");

                    b.HasIndex("MaThanhToan")
                        .IsUnique();

                    b.ToTable("ThanhToanOnline");
                });

            modelBuilder.Entity("quanlyphongkham.Models.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<string>("HinhThuc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KetQua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiThongBao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<int?>("MaLichHen")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoaiNhan")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("ThoiGianGui")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianHenGui")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaThongBao");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaLichHen");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("quanlyphongkham.Models.VatTu", b =>
                {
                    b.Property<int>("MaVatTu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVatTu"));

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("GiaNhap")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("HanSuDung")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoaiVatTu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NhaCungCap")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SoLuongToiThieu")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenVatTu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVatTu");

                    b.ToTable("VatTu");
                });

            modelBuilder.Entity("quanlyphongkham.Models.XuatKho", b =>
                {
                    b.Property<int>("MaXuatKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaXuatKho"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDoXuat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaHoSo")
                        .HasColumnType("int");

                    b.Property<int>("MaVatTu")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayXuat")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiXuat")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongXuat")
                        .HasColumnType("int");

                    b.HasKey("MaXuatKho");

                    b.HasIndex("MaHoSo");

                    b.HasIndex("MaVatTu");

                    b.HasIndex("NguoiXuat");

                    b.ToTable("XuatKho", t =>
                        {
                            t.HasTrigger("trg_CapNhatTonKhoXuat");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("quanlyphongkham.Models.YeuCauDatLich", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CoZalo")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("YeuCauDatLich");
                });

            modelBuilder.Entity("quanlyphongkham.Models.BacSi", b =>
                {
                    b.HasOne("quanlyphongkham.Models.NhanVien", "NhanVien")
                        .WithOne("BacSi")
                        .HasForeignKey("quanlyphongkham.Models.BacSi", "MaBacSi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("quanlyphongkham.Models.BaoCao", b =>
                {
                    b.HasOne("quanlyphongkham.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NguoiTao");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("quanlyphongkham.Models.BenhNhan", b =>
                {
                    b.HasOne("quanlyphongkham.Models.TaiKhoanNguoiDung", "TaiKhoanNguoiDung")
                        .WithMany("BenhNhans")
                        .HasForeignKey("MaTaiKhoan");

                    b.Navigation("TaiKhoanNguoiDung");
                });

            modelBuilder.Entity("quanlyphongkham.Models.CauHinhHeThong", b =>
                {
                    b.HasOne("quanlyphongkham.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NguoiCapNhat");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("quanlyphongkham.Models.ChamCong", b =>
                {
                    b.HasOne("quanlyphongkham.Models.NhanVien", "NhanVien")
                        .WithMany("ChamCongs")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("quanlyphongkham.Models.ChiTietHoSo", b =>
                {
                    b.HasOne("quanlyphongkham.Models.DichVu", "DichVu")
                        .WithMany("ChiTietHoSos")
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("quanlyphongkham.Models.HoSoBenhAn", "HoSoBenhAn")
                        .WithMany("ChiTietHoSos")
                        .HasForeignKey("MaHoSo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("HoSoBenhAn");
                });

            modelBuilder.Entity("quanlyphongkham.Models.GiaDichVu", b =>
                {
                    b.HasOne("quanlyphongkham.Models.DichVu", "DichVu")
                        .WithMany("GiaDichVus")
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");
                });

            modelBuilder.Entity("quanlyphongkham.Models.HinhAnhXQuang", b =>
                {
                    b.HasOne("quanlyphongkham.Models.HoSoBenhAn", "HoSoBenhAn")
                        .WithMany("HinhAnhXQuangs")
                        .HasForeignKey("MaHoSo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("quanlyphongkham.Models.NhanVien", "NhanVien")
                        .WithMany("HinhAnhXQuangs")
                        .HasForeignKey("NguoiUpload");

                    b.Navigation("HoSoBenhAn");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("quanlyphongkham.Models.HoSoBenhAn", b =>
                {
                    b.HasOne("quanlyphongkham.Models.BacSi", "BacSi")
                        .WithMany("HoSoBenhAns")
                        .HasForeignKey("MaBacSi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("quanlyphongkham.Models.BenhNhan", "BenhNhan")
                        .WithMany("HoSoBenhAns")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("quanlyphongkham.Models.GheNhaKhoa", "GheNhaKhoa")
                        .WithMany("HoSoBenhAns")
                        .HasForeignKey("MaGhe");

                    b.HasOne("quanlyphongkham.Models.LichHen", "LichHen")
                        .WithMany("HoSoBenhAns")
                        .HasForeignKey("MaLichHen");

                    b.Navigation("BacSi");

                    b.Navigation("BenhNhan");

                    b.Navigation("GheNhaKhoa");

                    b.Navigation("LichHen");
                });

            modelBuilder.Entity("quanlyphongkham.Models.LichBaoTriGhe", b =>
                {
                    b.HasOne("quanlyphongkham.Models.GheNhaKhoa", "GheNhaKhoa")
                        .WithMany("LichBaoTriGhes")
                        .HasForeignKey("MaGhe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("quanlyphongkham.Models.NhanVien", "NhanVien")
                        .WithMany("LichBaoTriGhes")
                        .HasForeignKey("NguoiBaoTri");

                    b.Navigation("GheNhaKhoa");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("quanlyphongkham.Models.LichHen", b =>
                {
                    b.HasOne("quanlyphongkham.Models.BacSi", "BacSi")
                        .WithMany("LichHens")
                        .HasForeignKey("MaBacSi")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("quanlyphongkham.Models.BenhNhan", "BenhNhan")
                        .WithMany("LichHens")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("quanlyphongkham.Models.DichVu", "DichVu")
                        .WithMany("LichHens")
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("quanlyphongkham.Models.GheNhaKhoa", "GheNhaKhoa")
                        .WithMany("LichHens")
                        .HasForeignKey("MaGhe");

                    b.HasOne("quanlyphongkham.Models.NhanVien", "NhanVienXacNhan")
                        .WithMany("LichHensXacNhan")
                        .HasForeignKey("MaNhanVienXacNhan");

                    b.HasOne("quanlyphongkham.Models.TaiKhoanNguoiDung", "TaiKhoanDatLich")
                        .WithMany("LichHens")
                        .HasForeignKey("MaTaiKhoanDatLich")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BacSi");

                    b.Navigation("BenhNhan");

                    b.Navigation("DichVu");

                    b.Navigation("GheNhaKhoa");

                    b.Navigation("NhanVienXacNhan");

                    b.Navigation("TaiKhoanDatLich");
                });

            modelBuilder.Entity("quanlyphongkham.Models.LichLamViec", b =>
                {
                    b.HasOne("quanlyphongkham.Models.NhanVien", "NhanVien")
                        .WithMany("LichLamViecs")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("quanlyphongkham.Models.Luong", b =>
                {
                    b.HasOne("quanlyphongkham.Models.NhanVien", "NhanVien")
                        .WithMany("Luongs")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("quanlyphongkham.Models.NhanVien", b =>
                {
                    b.HasOne("quanlyphongkham.Models.LoaiNhanVien", "LoaiNhanVien")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaLoaiNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("quanlyphongkham.Models.TaiKhoanNhanVien", "TaiKhoanNhanVien")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaTaiKhoanNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiNhanVien");

                    b.Navigation("TaiKhoanNhanVien");
                });

            modelBuilder.Entity("quanlyphongkham.Models.NhapKho", b =>
                {
                    b.HasOne("quanlyphongkham.Models.VatTu", "VatTu")
                        .WithMany("NhapKhos")
                        .HasForeignKey("MaVatTu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("quanlyphongkham.Models.NhanVien", "NhanVien")
                        .WithMany("NhapKhos")
                        .HasForeignKey("NguoiNhap");

                    b.Navigation("NhanVien");

                    b.Navigation("VatTu");
                });

            modelBuilder.Entity("quanlyphongkham.Models.PhanQuyen", b =>
                {
                    b.HasOne("quanlyphongkham.Models.LoaiNhanVien", "LoaiNhanVien")
                        .WithOne("PhanQuyen")
                        .HasForeignKey("quanlyphongkham.Models.PhanQuyen", "MaLoaiNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiNhanVien");
                });

            modelBuilder.Entity("quanlyphongkham.Models.QuanHeBenhNhan", b =>
                {
                    b.HasOne("quanlyphongkham.Models.BenhNhan", "BenhNhan")
                        .WithMany("QuanHeBenhNhans")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("quanlyphongkham.Models.TaiKhoanNguoiDung", "TaiKhoanNguoiDung")
                        .WithMany("QuanHeBenhNhans")
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BenhNhan");

                    b.Navigation("TaiKhoanNguoiDung");
                });

            modelBuilder.Entity("quanlyphongkham.Models.ThanhToan", b =>
                {
                    b.HasOne("quanlyphongkham.Models.HoSoBenhAn", "HoSoBenhAn")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaHoSo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("quanlyphongkham.Models.NhanVien", "NhanVien")
                        .WithMany("ThanhToans")
                        .HasForeignKey("NguoiThu");

                    b.Navigation("HoSoBenhAn");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("quanlyphongkham.Models.ThanhToanOnline", b =>
                {
                    b.HasOne("quanlyphongkham.Models.ThanhToan", "ThanhToan")
                        .WithOne("ThanhToanOnline")
                        .HasForeignKey("quanlyphongkham.Models.ThanhToanOnline", "MaThanhToan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThanhToan");
                });

            modelBuilder.Entity("quanlyphongkham.Models.ThongBao", b =>
                {
                    b.HasOne("quanlyphongkham.Models.BenhNhan", "BenhNhan")
                        .WithMany()
                        .HasForeignKey("MaBenhNhan");

                    b.HasOne("quanlyphongkham.Models.LichHen", "LichHen")
                        .WithMany()
                        .HasForeignKey("MaLichHen");

                    b.Navigation("BenhNhan");

                    b.Navigation("LichHen");
                });

            modelBuilder.Entity("quanlyphongkham.Models.XuatKho", b =>
                {
                    b.HasOne("quanlyphongkham.Models.HoSoBenhAn", "HoSoBenhAn")
                        .WithMany("XuatKhos")
                        .HasForeignKey("MaHoSo");

                    b.HasOne("quanlyphongkham.Models.VatTu", "VatTu")
                        .WithMany("XuatKhos")
                        .HasForeignKey("MaVatTu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("quanlyphongkham.Models.NhanVien", "NhanVien")
                        .WithMany("XuatKhos")
                        .HasForeignKey("NguoiXuat");

                    b.Navigation("HoSoBenhAn");

                    b.Navigation("NhanVien");

                    b.Navigation("VatTu");
                });

            modelBuilder.Entity("quanlyphongkham.Models.BacSi", b =>
                {
                    b.Navigation("HoSoBenhAns");

                    b.Navigation("LichHens");
                });

            modelBuilder.Entity("quanlyphongkham.Models.BenhNhan", b =>
                {
                    b.Navigation("HoSoBenhAns");

                    b.Navigation("LichHens");

                    b.Navigation("QuanHeBenhNhans");
                });

            modelBuilder.Entity("quanlyphongkham.Models.DichVu", b =>
                {
                    b.Navigation("ChiTietHoSos");

                    b.Navigation("GiaDichVus");

                    b.Navigation("LichHens");
                });

            modelBuilder.Entity("quanlyphongkham.Models.GheNhaKhoa", b =>
                {
                    b.Navigation("HoSoBenhAns");

                    b.Navigation("LichBaoTriGhes");

                    b.Navigation("LichHens");
                });

            modelBuilder.Entity("quanlyphongkham.Models.HoSoBenhAn", b =>
                {
                    b.Navigation("ChiTietHoSos");

                    b.Navigation("HinhAnhXQuangs");

                    b.Navigation("ThanhToans");

                    b.Navigation("XuatKhos");
                });

            modelBuilder.Entity("quanlyphongkham.Models.LichHen", b =>
                {
                    b.Navigation("HoSoBenhAns");
                });

            modelBuilder.Entity("quanlyphongkham.Models.LoaiNhanVien", b =>
                {
                    b.Navigation("NhanViens");

                    b.Navigation("PhanQuyen");
                });

            modelBuilder.Entity("quanlyphongkham.Models.NhanVien", b =>
                {
                    b.Navigation("BacSi");

                    b.Navigation("ChamCongs");

                    b.Navigation("HinhAnhXQuangs");

                    b.Navigation("LichBaoTriGhes");

                    b.Navigation("LichHensXacNhan");

                    b.Navigation("LichLamViecs");

                    b.Navigation("Luongs");

                    b.Navigation("NhapKhos");

                    b.Navigation("ThanhToans");

                    b.Navigation("XuatKhos");
                });

            modelBuilder.Entity("quanlyphongkham.Models.TaiKhoanNguoiDung", b =>
                {
                    b.Navigation("BenhNhans");

                    b.Navigation("LichHens");

                    b.Navigation("QuanHeBenhNhans");
                });

            modelBuilder.Entity("quanlyphongkham.Models.TaiKhoanNhanVien", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("quanlyphongkham.Models.ThanhToan", b =>
                {
                    b.Navigation("ThanhToanOnline");
                });

            modelBuilder.Entity("quanlyphongkham.Models.VatTu", b =>
                {
                    b.Navigation("NhapKhos");

                    b.Navigation("XuatKhos");
                });
#pragma warning restore 612, 618
        }
    }
}
